# Generated by Django 3.2.4 on 2023-05-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Mobiles', 'Mobiles'), ('Books&Sports', 'Books&Sports'), ('Jobs', 'Jobs'), ('Fashion', 'Fashion'), ('Property', 'Property'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Bikes', 'Bikes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MH', 'Maharashtra'), ('MI', 'Sikkim'), ('KA', 'Karnataka'), ('ML', 'Meghalaya'), ('AR', 'Arunachal Pradesh'), ('CG', 'Chhattisgarh'), ('MZ', 'Mizoram'), ('TN', 'Tamil Nadu'), ('BR', 'Bihar'), ('KL', 'Kerala'), ('MN', 'Manipur'), ('MP', 'Madhya Pradesh'), ('GJ', 'Gujarat'), ('HP', 'Haryana'), ('TR', 'Tripura'), ('JH', 'Jharkhand'), ('AP', 'Andhra Pradesh'), ('UP', 'Uttar Pradesh'), ('NL', 'Nagaland'), ('AS', 'Assam'), ('PB', 'Punjab'), ('OD', 'Odisha'), ('RJ', 'Rajasthan'), ('UK', 'Uttarakhand'), ('TS', 'Telangana'), ('GA', 'Goa'), ('WB', 'West Bengal')], max_length=100),
        ),
    ]
