# Generated by Django 3.2.4 on 2023-05-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20230525_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books&Sports', 'Books&Sports'), ('Jobs', 'Jobs'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Property', 'Property'), ('Bikes', 'Bikes'), ('Fashion', 'Fashion'), ('Cars', 'Cars')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MH', 'Maharashtra'), ('MZ', 'Mizoram'), ('AR', 'Arunachal Pradesh'), ('GJ', 'Gujarat'), ('KA', 'Karnataka'), ('ML', 'Meghalaya'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('UK', 'Uttarakhand'), ('MN', 'Manipur'), ('RJ', 'Rajasthan'), ('MP', 'Madhya Pradesh'), ('GA', 'Goa'), ('AP', 'Andhra Pradesh'), ('PB', 'Punjab'), ('JH', 'Jharkhand'), ('NL', 'Nagaland'), ('BR', 'Bihar'), ('TN', 'Tamil Nadu'), ('HP', 'Haryana'), ('TS', 'Telangana'), ('MI', 'Sikkim'), ('CG', 'Chhattisgarh'), ('KL', 'Kerala'), ('TR', 'Tripura'), ('AS', 'Assam'), ('OD', 'Odisha')], max_length=100),
        ),
    ]
