# Generated by Django 3.2.4 on 2023-05-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20230525_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Books&Sports', 'Books&Sports'), ('Property', 'Property'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Cars', 'Cars'), ('Mobiles', 'Mobiles'), ('Jobs', 'Jobs'), ('Fashion', 'Fashion'), ('Bikes', 'Bikes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('UK', 'Uttarakhand'), ('GJ', 'Gujarat'), ('PB', 'Punjab'), ('TR', 'Tripura'), ('CG', 'Chhattisgarh'), ('RJ', 'Rajasthan'), ('MN', 'Manipur'), ('MI', 'Sikkim'), ('WB', 'West Bengal'), ('MZ', 'Mizoram'), ('KA', 'Karnataka'), ('OD', 'Odisha'), ('HP', 'Haryana'), ('AS', 'Assam'), ('NL', 'Nagaland'), ('BR', 'Bihar'), ('UP', 'Uttar Pradesh'), ('KL', 'Kerala'), ('GA', 'Goa'), ('ML', 'Meghalaya'), ('TN', 'Tamil Nadu'), ('AR', 'Arunachal Pradesh'), ('TS', 'Telangana'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh'), ('JH', 'Jharkhand'), ('AP', 'Andhra Pradesh')], max_length=100),
        ),
    ]
